### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ionescu007/winipt#2]
I would like to point out that an identifier like “[`_IPT_MATCH_SETTINGS`](https://github.com/ionescu007/winipt/blob/e30e02bce05da061de1f7541a595caf936a76dc4/inc/libipt.h#L22 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by ionescu007** [comment]
Hi Markus,

Underscored identifiers are the coding convention of the NT kernel and I/O model, which IPT.SYS belongs to.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
