### ISSUE TITLE
Kernel Mode Tracing fails with error 87

### ISSUE THREAD

**Issue by TomSie** [ionescu007/winipt#4]
Good Morning,

first of all thank you for sharing your work with us!

I am experiencing problems when I try to start a kernel level trace: 
ipttool.exe --start <PID> 20000 4
and
ipttool.exe --start <PID> 20000 8

both fail with error 87(ERROR_INVALID_PARAMETER) on my machine.

My test system is a freshly setup Windows 10 1809 (Build 17763.1). ipt.sys is in version 10.0.17763.1

Is it just me, or is this a general problem (e.g. the API changed)?

Best regards

Tom

**Comment by ionescu007** [comment]
Yep, I am working on updating the project to support the final RS5 API.

Best regards,
Alex Ionescu

**Comment by ionescu007** [comment]
Ah, sorry, kernel-level traces are not yet supported by the Windows code yet. This is not a bug in winipt -- sorry :(
