### ISSUE TITLE
StartService failed GetLastError() ==50

### ISSUE THREAD

**Issue by vbty** [ionescu007/winipt#6]
Can i use this code in the Vmware workstation 15.0.2 build-10952284？

**Comment by chitoge** [comment]
AFAIK I think it's not possible as VMware doesn't emulate Intel PT functionalities in the guest CPU.

**Comment by ionescu007** [comment]
Correct, this only works on real hardware, and perhaps soon, Hyper-V. This may chance if other emulators eventually expose IPT.
